FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    avr-libc \
    bear \
    build-essential \
    cppcheck \
    gcc-avr \
    git \
    libcpptest-dev \
    pkg-config \
    uncrustify \
    unzip
